### ISSUE TITLE
having "py" stops AutoBanner.py from running

### ISSUE THREAD

**Issue by Rohul1997** [Ryuzaki-MrL/blargVC#6]
having py stops AutoBanner.py from running for some users
`py tools\autobanner.py "%title%"`

It should be:
`tools\autobanner.py "%title%"`

https://github.com/Ryuzaki-MrL/blargVC/blob/master/banner.bat#L110

**Comment by Ryuzaki-MrL** [comment]
Some users might not have python set to PATH, so yeah, you're right.

**Comment by Ryuzaki-MrL** [comment]
Fixed in 1a88255
