### ISSUE TITLE
banner.bat doesn't work

### ISSUE THREAD

**Issue by Crash-git** [Ryuzaki-MrL/blargVC#7]
When I try to run banner.bat, it fails at the automating screen. It just moves my mouse around, clicking random things. What is it supposed to be doing, and how do I fix it?

**Comment by Ryuzaki-MrL** [comment]
Is your screen resolution 1366x768? If so then make sure you're not touching anything after pressing enter.

**Comment by d4mation** [comment]
It requires a certain screen resolution? No wonder it didn't work for me. It just got into an endless loop that was very difficult to break out of (Since it was taking control of my mouse).

I ended up modifying the files and doing it manually instead.

**Comment by Crash-git** [comment]
My resolution is 1920x1080.

**Comment by Crash-git** [comment]
@d4mation how did you do it manually?

**Comment by d4mation** [comment]
@CrashMan054 

Your screen will look terrible, but it makes it work. Just change it to 1366x768 while using the program.

![image](https://cloud.githubusercontent.com/assets/7770631/18452422/c29129f0-7908-11e6-8c5e-42847f01184a.png)

**Comment by Crash-git** [comment]
Thank you!
