### ISSUE TITLE
I have some problems

### ISSUE THREAD

**Issue by IAMSolaara** [Ryuzaki-MrL/blargVC#8]
I try to make a banner but 1) It's not used, 2) My mouse goes in this triangle like pattern until Ohana closes.
Everything is okay except the banner. Why?

**Comment by IAMSolaara** [comment]
nevermind
just saw a closed issue and got this to work
still...
that way of making the banner is really clever
you should just tell this in the USAGE.TXT 👍 
I'd like to see your opinion
then feel free to close this

**Comment by Ryuzaki-MrL** [comment]
Thanks for the heads up. For now I'll put a warning about screen resolution on the README, until Asdolo releases his GUI solution.
